
# 3.2.2 Индексирование и вырезание

## Задание 1

Конечно, давайте создадим аналогичную задачу без использования изображения.

**Условие:**
Создайте целочисленный массив `ndarray` размера `(3,3)`. Представьте, что каждый элемент этого массива находится на черной позиции, как показано на следующей схеме:

```
B  W  B
W  B  W
B  W  B
```

Теперь, используя индексы элементов на черных позициях (B), выполните 4 выборки элементов согласно следующим выражениям:

1. Выборка элементов с индексами `(0, 0)`, `(1, 1)`, `(2, 2)`.
2. Выборка элементов с индексами `(0, 2)`, `(1, 1)`, `(2, 0)`.
3. Выборка элементов с индексами `(0, 1)`, `(1, 1)`, `(2, 1)`.
4. Выборка элементов с индексами `(1, 0)`, `(1, 1)`, `(1, 2)`.

Найдите максимальное значение в каждой из полученных выборок.

**Формат ответа:**
Кортеж чисел (например, `(3, 5, 2, 6)`).

**Решение:**

In [ ]:
import numpy as np

# Создание целочисленного массива размером (3, 3)
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Выбор элементов с черных позиций (B) согласно условию
black_indices = [(0,1), (1,0), (2,2)]

# Выборка элементов с индексами (0, 0), (1, 1), (2, 2)
selection1 = [array[idx] for idx in black_indices]

# Выборка элементов с индексами (0, 2), (1, 1), (2, 0)
selection2 = [array[2-idx[0], idx[1]] for idx in black_indices]

# Выборка элементов с индексами (0, 1), (1, 1), (2, 1)
selection3 = [array[idx[0], 1] for idx in black_indices]

# Выборка элементов с индексами (1, 0), (1, 1), (1, 2)
selection4 = [array[1, idx[1]] for idx in black_indices]

# Нахождение максимального значения в каждой выборке
max_value1 = max(selection1)
max_value2 = max(selection2)
max_value3 = max(selection3)
max_value4 = max(selection4)

print("Выборка элементов (0, 0), (1, 1), (2, 2):", selection1, "Максимальное значение:", max_value1)
print("Выборка элементов (0, 2), (1, 1), (2, 0):", selection2, "Максимальное значение:", max_value2)
print("Выборка элементов (0, 1), (1, 1), (2, 1):", selection3, "Максимальное значение:", max_value3)
print("Выборка элементов (1, 0), (1, 1), (1, 2):", selection4, "Максимальное значение:", max_value4)


Выборка элементов (0, 0), (1, 1), (2, 2): [2, 4, 9] Максимальное значение: 9
Выборка элементов (0, 2), (1, 1), (2, 0): [8, 4, 3] Максимальное значение: 8
Выборка элементов (0, 1), (1, 1), (2, 1): [2, 5, 8] Максимальное значение: 8
Выборка элементов (1, 0), (1, 1), (1, 2): [5, 4, 6] Максимальное значение: 6


## Задание 2

**Условие:**
Создайте случайный целочисленный массив ```ndarray``` из ```100``` элементов, принадлежащих отрезку ```[0,10]```. С помощью булевой индексации найдите все четные элементы в массиве. Найдите сумму полученных элементов. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```56```)

**Оценка в баллах:** 3 балла

**Решение:**

In [ ]:
import numpy as np

# Установка seed для воспроизводимости результатов
np.random.seed(1000)

# Создание случайного целочисленного массива из 100 элементов на отрезке [0, 10]
array = np.random.randint(0, 11, 100)

# Булевая индексация для нахождения четных элементов
even_elements = array[array % 2 == 0]

# Нахождение суммы четных элементов
sum_even_elements = np.sum(even_elements)

print("Случайный массив:", array)
print("Четные элементы:", even_elements)
print("Сумма четных элементов:", sum_even_elements)


Случайный массив: [ 3  7  7  0  1  0  9  8  9  4 10 10  9  4  4  2  9  8  2  4  2  5 10  5
  4  0  4  2  5 10  4  7  0  4  7  1  0  2  1  7  1  5  6  5  7  8  8  2
  2  9  6 10 10  3  3  6  5  8  4  1  0  9  1  8  8  0  2  9  3 10  9  6
  2  9  5  8  5  6  9  6  7  6  3  4  8  1  3  7  2  0  4  4  1  6  5  1
  4  1  7  4]
Четные элементы: [ 0  0  8  4 10 10  4  4  2  8  2  4  2 10  4  0  4  2 10  4  0  4  0  2
  6  8  8  2  2  6 10 10  6  8  4  0  8  8  0  2 10  6  2  8  6  6  6  4
  8  2  0  4  4  6  4  4]
Сумма четных элементов: 266


## Задание 3

**Условие:**
Создайте случайный целочисленный массив ndarray размера ```(10,10)``` элементов, принадлежащих отрезку ```[0,10]```. Сделайте подвыборку по всем строкам с нечетным индексом. Найдите сумму всех элементов в полученной матрице. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```150```)

**Оценка в баллах:** 4 балла


**Решение:**

In [ ]:
import numpy as np

# Установка seed для воспроизводимости результатов
np.random.seed(1000)

# Создание случайного целочисленного массива размером (10, 10) из элементов на отрезке [0, 10]
array = np.random.randint(0, 11, (10, 10))

# Выборка всех строк с нечетным индексом
sub_array = array[1::2]

# Нахождение суммы всех элементов в полученной матрице
sum_sub_array = np.sum(sub_array)

print("Исходный массив:")
print(array)
print("\nПодвыборка по строкам с нечетным индексом:")
print(sub_array)
print("\nСумма всех элементов в подвыборке:", sum_sub_array)


Исходный массив:
[[ 3  7  7  0  1  0  9  8  9  4]
 [10 10  9  4  4  2  9  8  2  4]
 [ 2  5 10  5  4  0  4  2  5 10]
 [ 4  7  0  4  7  1  0  2  1  7]
 [ 1  5  6  5  7  8  8  2  2  9]
 [ 6 10 10  3  3  6  5  8  4  1]
 [ 0  9  1  8  8  0  2  9  3 10]
 [ 9  6  2  9  5  8  5  6  9  6]
 [ 7  6  3  4  8  1  3  7  2  0]
 [ 4  4  1  6  5  1  4  1  7  4]]

Подвыборка по строкам с нечетным индексом:
[[10 10  9  4  4  2  9  8  2  4]
 [ 4  7  0  4  7  1  0  2  1  7]
 [ 6 10 10  3  3  6  5  8  4  1]
 [ 9  6  2  9  5  8  5  6  9  6]
 [ 4  4  1  6  5  1  4  1  7  4]]

Сумма всех элементов в подвыборке: 253
