
# 3.2.3 Уход от циклов: обработка данных с применением массивов

## Задание 1

**Условие:**
Создайте случайный целочисленный массив ```ndarray``` из ```12``` элементов, принадлежащих отрезку ```[0,10]```. Сделайте две матрицы размера ```(3,4)``` с порядком следования элементов в стиле С и Fortran. Найдите поэлементное произведение этих матриц, а после - максимальный элемент в полученной матрице. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```25```)



**Решение:**

In [ ]:
import numpy as np

# Установка seed для воспроизводимости результатов
np.random.seed(1000)

# Создание случайного целочисленного массива ndarray из 12 элементов на отрезке [0, 10]
array = np.random.randint(0, 11, 12)

# Создание двух матриц размером (3, 4) с порядком следования элементов в стиле C и Fortran
matrix_c = array.reshape(3, 4, order='C')
matrix_f = array.reshape(3, 4, order='F')

# Нахождение поэлементного произведения двух матриц
result_matrix = matrix_c * matrix_f

# Нахождение максимального элемента в полученной матрице
max_element = np.max(result_matrix)

print("Исходный массив:")
print(array)
print("\nМатрица в стиле C:")
print(matrix_c)
print("\nМатрица в стиле Fortran:")
print(matrix_f)
print("\nПолученная матрица после поэлементного умножения:")
print(result_matrix)
print("\nМаксимальный элемент в полученной матрице:", max_element)


Исходный массив:
[ 3  7  7  0  1  0  9  8  9  4 10 10]

Матрица в стиле C:
[[ 3  7  7  0]
 [ 1  0  9  8]
 [ 9  4 10 10]]

Матрица в стиле Fortran:
[[ 3  0  9  4]
 [ 7  1  8 10]
 [ 7  0  9 10]]

Полученная матрица после поэлементного умножения:
[[  9   0  63   0]
 [  7   0  72  80]
 [ 63   0  90 100]]

Максимальный элемент в полученной матрице: 100


## Задание 2

**Условие:**
Создайте ```3``` случайных целочисленных массива ```ndarray``` размера ```(10,10)``` элементов, принадлежащих отрезку ```[0,10]```. Сделайте из данных массивов один трехмерный массив. Найдя размер полученного массива, вычислите количество элементов в нем. Используйте ```np.random.seed(1000)``` перед генерацией массива для воспроизводимости результатов.

**Формат ответа:**
Число (например, ```56```)


**Решение:**

In [ ]:
import numpy as np

np.random.seed(1000)

# Создание трех случайных массивов размером (10, 10) в диапазоне [0, 10]
array1 = np.random.randint(0, 11, size=(10, 10))
array2 = np.random.randint(0, 11, size=(10, 10))
array3 = np.random.randint(0, 11, size=(10, 10))

# Объединение трех массивов в трехмерный массив
three_dim_array = np.array([array1, array2, array3])

# Нахождение размера полученного массива
shape = three_dim_array.shape

# Вычисление количества элементов в трехмерном массиве
num_elements = three_dim_array.size

print("Размер трехмерного массива:", shape)
print("Количество элементов в трехмерном массиве:", num_elements)


Размер трехмерного массива: (3, 10, 10)
Количество элементов в трехмерном массиве: 300


## Задание 3

**Условие:**
С использование методов ```ndarray``` сформируйте массив размера ```(20,2)```, в первом столбце которого идут целые числа, начиная с ```1```,а во втором - первые 20 нечетных чисел, начиная с ```3```. Найдите среднее значение второго столбца.

**Формат ответа:**
Число (например, ```34```)



**Решение:**

In [ ]:
import numpy as np

# Создание массива размера (20, 2) с первым столбцом - целыми числами, начиная с 1, и вторым столбцом - первыми 20 нечетными числами, начиная с 3
arr = np.zeros((20, 2), dtype=int)
arr[:, 0] = np.arange(1, 21)
arr[:, 1] = np.arange(3, 43, 2)

# Нахождение среднего значения второго столбца
mean_second_column = np.mean(arr[:, 1])

print("Массив размера (20, 2):")
print(arr)
print("Среднее значение второго столбца:", mean_second_column)


Массив размера (20, 2):
[[ 1  3]
 [ 2  5]
 [ 3  7]
 [ 4  9]
 [ 5 11]
 [ 6 13]
 [ 7 15]
 [ 8 17]
 [ 9 19]
 [10 21]
 [11 23]
 [12 25]
 [13 27]
 [14 29]
 [15 31]
 [16 33]
 [17 35]
 [18 37]
 [19 39]
 [20 41]]
Среднее значение второго столбца: 22.0
